
server.port=${PORT:8080}

spring.application.name=softdevoluciones-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/softdevoluciones_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:posgre123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:Xk9mP2vQ7rT4wZ8bN3cL6hJ1yD5sF0gAuE7iO2kR9tV4xM8nB3qW6zC1pL5jH0sY}
jwt.expiration=${JWT_EXPIRATION:86400000}

server.error.include-message=always
server.error.include-stacktrace=always

